title: Fernando Meneses
email: fertmeneses@gmail.com
logo: assets/logo.png
description: Physicist | ML engineer | Data scientist
show_downloads: True
google_analytics: 10229869659
#theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
